<a href="https://colab.research.google.com/github/dioallan/testecolab/blob/main/Untitled17.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [31]:
#Import das bibliotecas do Pandas, Matplotlib e Seaborn

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [ ]:
#Import das duas bases baixadas do site Gapminder
Desemprego = pd.read_csv("/content/desemprego.csv")
Inflacao = pd.read_csv("/content/inflacao.csv")

In [ ]:
#Pre Analise das bases:
Desemprego.head()

,country,1948,1949,1950,1951,1952,1953,1954,1955,1956,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,Aruba,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.09,NaN,6.73,NaN,NaN,8.4,NaN,NaN,9.89
2,Angola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.25,NaN,NaN,8.44,NaN,NaN,NaN,NaN,NaN,NaN
3,Anguilla,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Albania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.20,12.20,15.3,16.40,15.5,13.9,12.5,11.2,10.6,NaN

In [ ]:
#Pre Analise das bases:
Inflacao.head()

,country,1961,1962,1963,1964,1965,1966,1967,1968,1969,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,Aruba,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.96,6.83,âˆ’1,âˆ’3.18,3.48,6.09,âˆ’0.871,âˆ’4.99,3.41,NaN
1,Afghanistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.567,2.45,âˆ’2.2,2.4,2.07,6.52,6.96,2.84,9.41,NaN
2,Angola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.56,âˆ’3.52,21.8,22.6,28.2,19.2,10.8,38.8,13.7,17.6
3,Albania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.55,0.564,âˆ’0.633,1.45,1.47,1.26,0.697,3.45,9.87,4.55
4,Andorra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,âˆ’0.084,0.661,0.348,1.14,1.01,1.37,1.11,2.56,4.24,5.86

In [ ]:
#Criando novos datasets com algumas colunas, no exercicÃ­o irei trabalhar somente de 2015 atÃ© 2019, ultimo ano da base
Desem = Desemprego[["country","2015","2016","2017","2018","2019"]]
Infl = Inflacao[["country","2015","2016","2017","2018","2019"]]

In [ ]:
Infl.head()

In [ ]:
Desem.head()

In [ ]:
Desem.shape

In [ ]:
Infl.shape

In [ ]:
Desem.isnull().sum()

In [ ]:
Infl.isnull().sum()

In [ ]:
#Rename das colunas do dataset de InflaÃ§Ã£o

Infl = Infl.rename(columns={'country':'Pais','2015':'Infla2015','2016':'Infla2016','2017':'Infla2017','2018':'Infla2018',
                             '2019':'Infla2019'})

In [ ]:
#Rename das colunas do dataset de Desemprego
Desem = Desem.rename(columns={'country':'Pais','2015':'Desemp2015','2016':'Desemp2016','2017':'Desemp2017','2018':'Desemp2018',
                             '2019':'Desemp2019'})

In [ ]:
#Replace do caracter 'âˆ’' presente na base de inflaÃ§Ã£o para nÃºmeros
#negativos, que acaba sendo interpretado como string e nÃ£o deixando fazer a conversÃ£o para float, nessa coloco o
#sinal correto para ser de fato um nÃºmero negativo '-'
Infl['Infla2015'] = Infl['Infla2015'].str.replace('âˆ’', '-')
Infl['Infla2016'] = Infl['Infla2016'].str.replace('âˆ’', '-')
Infl['Infla2017'] = Infl['Infla2017'].str.replace('âˆ’', '-')
Infl['Infla2018'] = Infl['Infla2018'].str.replace('âˆ’', '-')
Infl['Infla2019'] = Infl['Infla2019'].str.replace('âˆ’', '-')

In [ ]:
#ConversÃ£o dos valores antes String da base de inflaÃ§Ã£o para float
Infl['Infla2015'] = Infl['Infla2015'].astype(float)
Infl['Infla2016'] = Infl['Infla2016'].astype(float)
Infl['Infla2017'] = Infl['Infla2017'].astype(float)
Infl['Infla2018'] = Infl['Infla2018'].astype(float)
Infl['Infla2019'] = Infl['Infla2019'].astype(float)

In [ ]:
#Substituindo os valores nulos presentes na base de inflaÃ§Ã£o por 0
Infl['Infla2015'] = Infl['Infla2015'].fillna(0)
Infl['Infla2016'] = Infl['Infla2016'].fillna(0)
Infl['Infla2017'] = Infl['Infla2017'].fillna(0)
Infl['Infla2018'] = Infl['Infla2018'].fillna(0)
Infl['Infla2019'] = Infl['Infla2019'].fillna(0)

In [ ]:
#Substituindo os valores nulos presentes na base de Deseprego por 0
Desem['Desemp2015'] = Desem['Desemp2015'].fillna(0)
Desem['Desemp2016'] = Desem['Desemp2016'].fillna(0)
Desem['Desemp2017'] = Desem['Desemp2017'].fillna(0)
Desem['Desemp2018'] = Desem['Desemp2018'].fillna(0)
Desem['Desemp2019'] = Desem['Desemp2019'].fillna(0)

In [ ]:
Infl.head()

In [ ]:
Desem.head()

In [ ]:
Infl.isnull().sum()

In [ ]:
Desem.isnull().sum()

In [ ]:
# Criando um dataset final atravÃ©s de um merge usando como referÃªncia a variÃ¡vel "Pais"
Tabfinal = Desem.merge(Infl, how='left', on='Pais')

In [ ]:
#Criando um campo "Media inflaÃ§Ã£o" e "Media Desemprego" em seus respectivos datasets e fazendo o calculo da
#media de cada Pais de 2015 Ã  2019
Desem['Media Desemprego'] = Desem.mean(axis = 1)
Infl['Media InflaÃ§Ã£o'] = Infl.mean(axis = 1)